spring:
  security:
    users:
      - username: admin
        # Passwords should be encoded using BCrypt
        password: $2a$10$CXLerA.8Xn11PsulfRH87O.ycwHupuLI4S.QdQikqNxJTzXcoTZ7i
        roles: ADMIN,MANAGER,USER
      - username: manager
        password: manager543
        roles: MANAGER,USER
      - username: user
        password: user654
        roles: USER
      - username: guest
        password: guest543
        roles: GUEST
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        registration:
          skygeo-client:
            provider: spring
            client-id: skygeo-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/skygeo-client"
            scope: openid,read,write
        provider:
          spring:
            issuer-uri: http://localhost:9000
  main:
    allow-bean-definition-overriding: true